# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todologinapp' do

pod 'Firebase/AdMob'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Invites'
pod 'Firebase/Messaging'
pod 'Firebase/Performance'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
  
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
